@echo OFF
::
:: This file is generated by configure.bat
::

set TFDIR=C:\TreeFrog\1.16.0
set QTENV="C:\Qt\5.7\mingw53_32\bin\qtenv2.bat"
set QMAKESPEC=
if exist %QTENV% ( call %QTENV% )
set PATH=%TFDIR%\bin;%PATH%
echo Setup a TreeFrog/Qt environment.
echo -- TFDIR set to %TFDIR%
cd /D %HOMEDRIVE%%HOMEPATH%
