@echo OFF
::
:: This file is generated by configure.bat
::

set TFDIR=D:\TreeFrog\1.16.0
set QTENV="D:\Qt\Qt5.4.1\5.4\mingw491_32\bin\qtenv2.bat"
set QMAKESPEC=
if exist %QTENV% ( call %QTENV% )
set PATH=%TFDIR%\bin;%PATH%
echo Setup a TreeFrog/Qt environment.
echo -- TFDIR set to %TFDIR%
cd /D %HOMEDRIVE%%HOMEPATH%
