// Generated by ResEdit 1.5.11
// Copyright (C) 2006-2012
// http://www.resedit.net

#include <windows.h>
#include <commctrl.h>
#include <richedit.h>
#include "resource.h"

//
// User resources
//
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL
IDR_TREEFROG_MSI   TREEFROG_MSI   "C:\\Users\\aoyama\\Documents\\treefrog-framework\\installer\\TreeFrog-1.x.x.msi"


//
// Dialog resources
//
//LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL
//IDD_DIALOG1 DIALOG 0, 0, 262, 149
//STYLE DS_3DLOOK | DS_CENTER | DS_MODALFRAME | DS_SHELLFONT | WS_CAPTION | WS_VISIBLE | WS_POPUP | WS_SYSMENU
//CAPTION "Qt Base Directory"
//FONT 11, "MS UI Gothic"
//BEGIN
//    DEFPUSHBUTTON   "Continue", IDOK, 142, 117, 50, 18
//    PUSHBUTTON      "Cancel", IDCANCEL, 200, 117, 50, 18
//    EDITTEXT        IDC_EDIT1, 25, 55, 173, 19, ES_AUTOHSCROLL
//    PUSHBUTTON      "Browse...", IDC_BROWSE1, 206, 55, 43, 19
//    LTEXT           "Specify the base directory of Qt version 5.", IDC_STATIC, 23, 17, 149, 14, SS_LEFT
//    LTEXT           "Example:  C:\\Qt\\Qt5.0.2", IDC_STATIC, 29, 30, 76, 8, SS_LEFT
//END


//
// Icon resources
//
LANGUAGE 17, SUBLANG_DEFAULT
1                  ICON           "app.ico"


//
// String Table resources
//
//LANGUAGE LANG_JAPANESE, SUBLANG_JAPANESE_JAPAN
STRINGTABLE
BEGIN
    IDS_APP_TITLE                 "treefrogsetup"
END

