DROP TABLE IF EXISTS blog;
CREATE TABLE blog (id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(20), body VARCHAR(200), created_at TIMESTAMP, updated_at TIMESTAMP);
DROP TABLE IF EXISTS food;
CREATE TABLE food (food_name VARCHAR(20) PRIMARY KEY, price_yen INTEGER, lock_revision INTEGER);
DROP TABLE IF EXISTS book;
CREATE TABLE book (titleName VARCHAR(20) PRIMARY KEY, janCode VARCHAR(20), author VARCHAR(20), created_at TIMESTAMP, updated_at TIMESTAMP, lock_revision INTEGER);
