source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
group :jekyll_plugins do
  gem "markdown"
  gem "jekyll-theme-slate"
  gem 'execjs'
  gem 'therubyracer'
  gem "jekyll", "3.9.0"
end


gem "sass", "~> 3.7"
