source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
group :jekyll_plugins do
  gem "markdown"
  gem "jekyll-theme-slate"
  gem "jekyll", "3.9.4"
  #gem "liquid", ">= 4.0.0"
  #gem "jekyll-sass-converter", "~> 1.5.0"
end

gem "webrick", "~> 1.8"
